version: '3'
services:
  p4f-api:
    image: p4f:1.0
    ports: 
      - "5000:5000"
    container_name: 'p4f-Container'
    restart: always
    networks: 
      - p4f

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - p4f

  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Chalermwut13
    networks: 
      - p4f
      
networks: 
  p4f:


  jenkins:
    image: jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    # uncomment for docker in docker
    privileged: true
    volumes:
        # enable persistent volume (warning: make sure that the local jenkins_home folder is created)
        - /var/wisestep/data/jenkins_home:/var/jenkins_home
        # mount docker sock and binary for docker in docker (only works on linux)
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
